[package]
name = "test_mode"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

uuid = { workspace = true, features = ["v4", "serde"] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
hyper = { workspace = true, features = ["full"] }
headers = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
url = { workspace = true, features = ["serde"] }

thiserror = { workspace = true }
error-stack = { workspace = true }

async-trait = { workspace = true }


time = { workspace = true }

base64 = { workspace = true }


rand = { workspace = true }
nix = { workspace = true, default-features = false, features = ["signal"] }
image = { workspace = true, default-features = false, features = ["jpeg"] }
tokio-tungstenite = { workspace = true }

api_client = { path = "../api_client" }

utils = { path = "../utils" }
config = { path = "../config" }
simple_backend_config = { path = "../simple_backend_config" }
