[package]
name = "test_mode"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

uuid = { version = "1.1.2", features = ["v4", "serde"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7.2"

futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["sync"] }
hyper = { version = "0.14", features = ["full"] }
headers = "0.3.8"
reqwest = { version = "0.11", features = ["json"] }
url = { version = "2.3.1", features = ["serde"] }

thiserror = "1.0.37"
error-stack = "0.4"

async-trait = "0.1.66"


time = "0.3.20"

base64 = "0.21.0"


rand = "0.8.5"
nix = { version = "0.26.2", default-features = false, features = ["signal"] }
image = { version = "0.24.6", default-features = false, features = ["jpeg"] }
tokio-tungstenite = "0.19.0"

api_client = { path = "../api_client" }

utils = { path = "../utils" }
config = { path = "../config" }
simple_backend_config = { path = "../simple_backend_config" }
