[package]
name = "test_mode"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { workspace = true }

reqwest = { workspace = true }

config = { path = "../config" }
test_mode_bot = { path = "../test_mode_bot" }
test_mode_tests = { path = "../test_mode_tests" }
test_mode_tests_account = { path = "../test_mode_tests_account" }
test_mode_tests_profile = { path = "../test_mode_tests_profile" }
test_mode_tests_media = { path = "../test_mode_tests_media" }
