[package]
name = "simple_backend"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# For tokio-console debugging. Disabled currently
# console-subscriber = { workspace = true }

serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
chrono = { workspace = true }

tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }

hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["ws", "macros"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace"] }
reqwest = { workspace = true, features = ["json"] }
reqwest_headers = { workspace = true }

utoipa-swagger-ui = { workspace = true, features = ["axum"] }

# Email sending
lettre = { workspace = true }

# Server TLS
tokio-rustls = { workspace = true }
rustls-acme = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

jsonwebtoken = { workspace = true }

manager_api = { path = "../app-manager/crates/manager_api" }
manager_model = { path = "../app-manager/crates/manager_model" }

simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_database = { path = "../simple_backend_database" }
simple_backend_model = { path = "../simple_backend_model" }
