[package]
name = "simple_backend"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# For tokio-console debugging. Disabled currently
# console-subscriber = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }

hyper = { workspace = true }
hyper-util = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
reqwest = { workspace = true }
headers = { workspace = true }

utoipa-swagger-ui = { workspace = true }

# File hosting package
flate2 = { workspace = true }
tar = { workspace = true }
mime = { workspace = true }
regex = { workspace = true }

# Email sending
lettre = { workspace = true }

maxminddb = { workspace = true }

# Server TLS
tokio-rustls = { workspace = true }
tokio-rustls-acme = { workspace = true }
rustls-platform-verifier = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

jsonwebtoken = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }

sysinfo = { workspace = true }

manager_api = { path = "../manager_api" }
manager_model = { path = "../manager_model" }

simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_database = { path = "../simple_backend_database" }
simple_backend_model = { path = "../simple_backend_model" }
simple_backend_image_process = { path = "../simple_backend_image_process" }
