[package]
name = "simple_backend"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { workspace = true, features = ["v4", "serde"] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["io"]}
hyper = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["headers", "ws", "macros"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
headers = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
http = { workspace = true }

# For tokio-console debugging
console-subscriber = { workspace = true }

utoipa = { workspace = true, features = ["axum_extras", "uuid"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }

# Server TLS
tokio-rustls = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

async-trait = { workspace = true }

time = { workspace = true }
nalgebra = { workspace = true }

jsonwebtoken = { workspace = true }

num_cpus = { workspace = true }
nix = { workspace = true, default-features = false, features = ["signal"] }

manager_api = { path = "../app-manager/crates/manager_api" }
manager_model = { path = "../app-manager/crates/manager_model" }

simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_database = { path = "../simple_backend_database" }
simple_backend_model = { path = "../simple_backend_model" }
