[package]
name = "server_data_chat"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync", "fs"] }
tokio-util = { workspace = true, features = ["io"]}
axum = { workspace = true, features = ["ws", "macros"] }
tracing = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

nalgebra = { workspace = true }

num_cpus = { workspace = true }

config = { path = "../config" }
model = { path = "../model" }
server_common = { path = "../server_common" }
server_data = { path = "../server_data" }

database_chat = { path = "../database_chat" }

simple_backend = { path = "../simple_backend" }
simple_backend_utils = { path = "../simple_backend_utils" }
