[package]
name = "server_data_chat"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { workspace = true }

model = { path = "../model" }
model_chat = { path = "../model_chat" }
server_common = { path = "../server_common" }
server_data = { path = "../server_data" }

database = { path = "../database" }
database_chat = { path = "../database_chat" }

simple_backend_utils = { path = "../simple_backend_utils" }
