[package]
name = "simple_backend_config"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["cargo", "derive"] }

serde = { version = "1.0", features = ["derive"] }
toml = "0.7.2"

tracing = "0.1"
reqwest = { version = "0.11" }
url = { version = "2.3.1", features = ["serde"] }

# Server TLS
tokio-rustls = "0.24.0"
rustls-pemfile = "1.0.2"

thiserror = "1.0.37"
error-stack = "0.4"

simple_backend_utils = { path = "../simple_backend_utils" }
