[package]
name = "simple_backend_config"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["cargo", "derive"] }

serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

reqwest = { workspace = true }
url = { workspace = true, features = ["serde"] }

# Server TLS
tokio-rustls = { workspace = true }
rustls-pemfile = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

simple_backend_utils = { path = "../simple_backend_utils" }
