[workspace]
workspace.resolver = "2"
members = [
    # From git submodule
    "crates/app-manager/crates/manager_model",
    "crates/app-manager/crates/manager_api",
    # Binary crates
    "crates/pihka-backend",
    # Library crates
    "crates/api_client",
    "crates/api_internal",
    "crates/model",
    "crates/config",
    "crates/utils",
    "crates/test_mode",
    "crates/database",
    "crates/server",
    "crates/image_process"
]
