[workspace]
resolver = "2"
members = [
    # From git submodule
    "crates/app-manager/crates/manager_model",
    "crates/app-manager/crates/manager_api",
    # Binary crates
    "crates/pihka-backend",
    # Library crates
    "crates/api_client",
    "crates/api_internal",
    "crates/model",
    "crates/config",
    "crates/utils",
    "crates/test_mode",
    "crates/database",
    "crates/server",
    "crates/image_process",
    "crates/simple_backend",
    "crates/simple_backend_config",
    "crates/simple_backend_utils",
    "crates/simple_backend_database",
    "crates/simple_backend_model",
]

# Make image processing faster for debug builds
[profile.dev.package.image]
opt-level = 3

# TODO: Remove this before production?
[profile.release]
debug = true
