[workspace]
resolver = "2"
members = [
    # From git submodule
    "crates/app-manager/crates/manager_model",
    "crates/app-manager/crates/manager_api",
    # Binary crates
    "crates/pihka-backend",
    # Library crates
    "crates/api_client",
    "crates/api_internal",
    "crates/model",
    "crates/config",
    "crates/utils",
    "crates/test_mode",
    "crates/database",
    "crates/server",
    "crates/simple_backend",
    "crates/simple_backend_image_process",
    "crates/simple_backend_config",
    "crates/simple_backend_utils",
    "crates/simple_backend_database",
    "crates/simple_backend_model",
]

[workspace.dependencies]

# Build dependencies
vergen = { version = "8.0.0", features = ["cargo", "git", "gitcl", "rustc"] }


error-stack = "0.4"
thiserror = "1.0.37"

rand = "0.8.5"
time = "0.3.20"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
base64 = "0.21.0"
nalgebra = "0.32.2"
num_cpus = "1.16.0"
nix = { version = "0.26.2", default-features = false, features = ["signal"] }
image = { version = "0.24.6", default-features = false, features = ["jpeg"] }
mozjpeg = "0.10.1"
kamadak-exif = "0.5.5"

clap = { version = "4.4", features = ["cargo", "derive"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# For tokio-console debugging
console-subscriber = "0.2.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7.2"
toml_edit = "0.19.14"

sqlx = { version = "0.7.1", features = [ "runtime-tokio-rustls", "sqlite", "uuid" ] }
diesel = { version = "2.1.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1.0"
deadpool = { version = "0.9.0" }
deadpool-diesel = { version = "0.4.1", features = ["sqlite"] }

futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["sync"] }
tokio-util = { version = "0.7.7", features = ["io"]}
async-trait = "0.1.66"

reqwest = { version = "0.11", features = ["json"] }
utoipa = { version = "3.0.1", features = ["axum_extras", "uuid"] }
utoipa-swagger-ui = { version = "3.0.1", features = ["axum"] }
url = { version = "2.3.1", features = ["serde"] }
http = "0.2.9"
headers = "0.3.8"
jsonwebtoken = "8.3.0"
hyper = { version = "0.14", features = ["full"] }
axum = { version = "0.6", features = ["headers", "ws", "macros"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tokio-tungstenite = "0.19.0"

# Server TLS
tokio-rustls = "0.24.0"
rustls-pemfile = "1.0.2"


# Make image processing faster for debug builds
[profile.dev.package.image]
opt-level = 3

# TODO: Remove this before production?
[profile.release]
debug = true
