[workspace]
members = [
    # From git submodule
    "crates/app-manager/app-manager",
    "crates/app-manager/manager_api_client",
    # Binary crates
    "crates/pihka-backend",
    # Library crates
    "crates/api_client",
    "crates/api_internal",
    "crates/model",
    "crates/config",
    "crates/utils",
    "crates/test_mode",
    "crates/database",
    "crates/server",
]
