[package]
name = "pihka-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["cargo"] }
git2 = "0.15.0"
uuid = { version = "1.1.2", features = ["v4"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.10"
hyper = { version = "0.14", features = ["full"] }
axum = { version = "0.5", features = ["headers"] }
tower = "0.4.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mime = "0.3"
headers = "0.3.8"

utoipa = { version = "2.0.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "2.0.1", features = ["axum"] }


sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite" ] }
