[workspace]
resolver = "2"
members = [
    # From git submodule
    "crates/app-manager/crates/manager_model",
    "crates/app-manager/crates/manager_api",
    # Binary crates
    "crates/pihka-backend",
    # Library crates
    "crates/api_client",
    "crates/api_internal",
    "crates/model",
    "crates/config",
    "crates/utils",
    "crates/test_mode",
    "crates/test_mode_macro",
    "crates/database",
    "crates/database_chat",
    "crates/database_profile",
    "crates/database_media",
    "crates/database_account",
    "crates/server",
    "crates/server_common",
    "crates/server_api",
    "crates/server_data",
    "crates/server_data_chat",
    "crates/server_data_profile",
    "crates/server_data_media",
    "crates/server_data_account",
    "crates/simple_backend",
    "crates/simple_backend_image_process",
    "crates/simple_backend_config",
    "crates/simple_backend_utils",
    "crates/simple_backend_database",
    "crates/simple_backend_model",
]

[workspace.dependencies]

# Build dependencies
vergen = { version = "8.3.1", features = ["cargo", "git", "gitcl", "rustc"] }

error-stack = "0.4.1"
thiserror = "1.0.56"

rand = "0.8.5"
time = "0.3.34"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
base64 = "0.21.7"
nalgebra = "0.32.3"
num_cpus = "1.16.0"
nix = { version = "0.27.1", default-features = false, features = ["signal"] }
image = { version = "0.24.8", default-features = false, features = ["jpeg"] }
mozjpeg = "0.10.6"
kamadak-exif = "0.5.5"
bitflags = "2.4.2"
sha2 = "0.10.8"

clap = { version = "4.4.18", features = ["cargo", "derive"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
# For tokio-console debugging. Disabled currently.
# If you want to enable this uncomment also .cargo
# console-subscriber = "0.2.0"

serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
toml = "0.8.9"
toml_edit = "0.21.1"

diesel = { version = "2.1.4", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1.0"
deadpool = { version = "0.10.0" }
deadpool-diesel = { version = "0.5.0", features = ["sqlite"] }

futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["sync", "fs"] }
tokio-util = { version = "0.7.10", features = ["io"]}
async-trait = "0.1.77"

reqwest = { version = "0.11.24", features = ["json"] }
reqwest_headers = { package = "headers", version = "0.3.9" }
utoipa = { version = "4.2.0", features = ["axum_extras", "uuid"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }
url = { version = "2.5.0", features = ["serde"] }
http = "1.0.0"
headers = "0.4.0"
jsonwebtoken = "9.2.0"
hyper = { version = "1.1.0", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["full"] }
axum = { version = "0.7.4", features = ["ws", "macros"] }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["trace"] }

# Server TLS
tokio-rustls = "0.25.0"
rustls-pemfile = "2.0.0"
rustls-acme = { version = "0.9.2", features = ["tokio"] }

# Test mode macro
syn = { version = "2.0.48", features = ["full"] }
quote = "1.0.35"

# Test mode
inventory = "0.3.15"
tokio-tungstenite = { version = "0.21.0", features = ["rustls-tls-native-roots"] }

# Firebase cloud messaging
[workspace.dependencies.fcm]
git = "https://github.com/jutuon/fcm-rust"
rev = "bbbd91c5e7724dbc0c326052241dcebbe1b23884"

# Make image processing faster for debug builds
[profile.dev.package.image]
opt-level = 3

# TODO(prod): Remove this before production?
[profile.release]
debug = true

# Improve build time
[profile.dev]
debug = 0
strip = "debuginfo"
panic = "abort"
