[package]
name = "simple_backend_image_process"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { workspace = true, default-features = false, features = ["jpeg"] }
mozjpeg = { workspace = true }
rustface = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

simple_backend_config = { path = "../simple_backend_config" }
