[package]
name = "database"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { version = "1.1.2", features = ["v4", "serde"] }

serde_json = "1.0"

futures = "0.3.28"
tokio-stream = { version = "0.1.10", features = ["sync"] }

sqlx = { version = "0.7.1", features = [ "runtime-tokio-rustls", "sqlite", "uuid" ] }

diesel = { version = "2.1.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1.0"

error-stack = "0.4"

time = "0.3.20"

model = { path = "../model" }

simple_backend_config = { path = "../simple_backend_config" }
simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_database = { path = "../simple_backend_database" }
