[package]
name = "database"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { version = "1.1.2", features = ["v4", "serde"] }

serde_json = "1.0"

futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["sync"] }
tracing = "0.1"

sqlx = { version = "0.7.1", features = [ "runtime-tokio-rustls", "sqlite", "uuid" ] }

diesel = { version = "2.1.0", features = ["sqlite"] }
diesel_migrations = "2.1.0"
deadpool = { version = "0.9.0" }
deadpool-diesel = { version = "0.4.1", features = ["sqlite"] }


num_cpus = "1.16.0"

thiserror = "1.0.37"
error-stack = "0.2.3"

async-trait = "0.1.66"

time = "0.3.20"

utils = { path = "../utils" }
config = { path = "../config" }
model = { path = "../model" }
