[package]
name = "config"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["cargo"] }

serde = { version = "1.0", features = ["derive"] }
toml = "0.7.2"

tracing = "0.1"
reqwest = { version = "0.11" }
url = { version = "2.3.1", features = ["serde"] }

# Server TLS
tokio-rustls = "0.24.0"
rustls-pemfile = "1.0.2"

thiserror = "1.0.37"
error-stack = "0.2.3"

utils = { path = "../utils" }
