[package]
name = "config"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["cargo", "derive"] }

serde = { version = "1.0", features = ["derive"] }
toml = "0.7.2"
toml_edit = "0.19.14"

reqwest = { version = "0.11" }
url = { version = "2.3.1", features = ["serde"] }

thiserror = "1.0.37"
error-stack = "0.4"

model = { path = "../model" }

simple_backend_config = { path = "../simple_backend_config" }
simple_backend_utils = { path = "../simple_backend_utils" }
