use diesel::sql_types::SmallInt;
pub use minimal_i64::add_minimal_i64;
use model::{AccountId, MessageNumber, PublicKeyId, UnixTime};
use num_enum::TryFromPrimitive;
use serde::{Deserialize, Serialize};
use simple_backend_model::SimpleDieselEnum;
use simple_backend_utils::UuidBase64Url;
use utils::minimal_i64;
use utoipa::ToSchema;

use crate::MessageId;

pub struct SignedMessageData {
    /// Sender of the message.
    pub sender: AccountId,
    /// Recipient of the message.
    pub recipient: AccountId,
    /// Message UUID generated by sender.
    pub message_id: MessageId,
    pub sender_public_key_id: PublicKeyId,
    pub recipient_public_key_id: PublicKeyId,
    pub m: MessageNumber,
    /// Unix time when server received the message.
    pub unix_time: UnixTime,
    pub message: Vec<u8>,
}

impl SignedMessageData {
    pub fn parse(data: &[u8]) -> Result<Self, String> {
        Self::parse_internal(data).ok_or("Parsing failure: not enough data".to_string())?
    }

    fn parse_internal(data: &[u8]) -> Option<Result<Self, String>> {
        let mut d = data.iter().copied();

        let version = d.next()?;
        if version != 1 {
            return Some(Err(format!("Data version {version}, expected: 1")));
        }
        let sender = parse_account_id(&mut d)?;
        let recipient = parse_account_id(&mut d)?;
        let message_id = parse_message_id(&mut d)?;
        let sender_public_key_id = minimal_i64::parse_minimal_i64_from_iter(&mut d)?;
        let recipient_public_key_id = minimal_i64::parse_minimal_i64_from_iter(&mut d)?;
        let mn = minimal_i64::parse_minimal_i64_from_iter(&mut d)?;
        let ut = minimal_i64::parse_minimal_i64_from_iter(&mut d)?;
        let message = d.collect();

        Some(Ok(SignedMessageData {
            sender,
            recipient,
            message_id,
            sender_public_key_id: PublicKeyId {
                id: sender_public_key_id,
            },
            recipient_public_key_id: PublicKeyId {
                id: recipient_public_key_id,
            },
            m: MessageNumber { mn },
            unix_time: UnixTime { ut },
            message,
        }))
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        let mut bytes: Vec<u8> = vec![];
        // Version
        bytes.push(1);
        // Sender UUID big-endian bytes (16 bytes)
        bytes.extend_from_slice(self.sender.aid.as_bytes());
        // Recipient UUID big-endian bytes (16 bytes)
        bytes.extend_from_slice(self.recipient.aid.as_bytes());
        // Message UUID big-endian bytes (16 bytes)
        bytes.extend_from_slice(self.message_id.id().as_bytes());
        minimal_i64::add_minimal_i64(&mut bytes, self.sender_public_key_id.id);
        minimal_i64::add_minimal_i64(&mut bytes, self.recipient_public_key_id.id);
        minimal_i64::add_minimal_i64(&mut bytes, self.m.mn);
        minimal_i64::add_minimal_i64(&mut bytes, self.unix_time.ut);
        // Sent message data
        bytes.extend_from_slice(&self.message);
        bytes
    }
}

fn parse_account_id(d: &mut impl Iterator<Item = u8>) -> Option<AccountId> {
    let bytes: Vec<u8> = d.by_ref().take(16).collect();
    let bytes = TryInto::<[u8; 16]>::try_into(bytes).ok()?;
    Some(AccountId::new_base_64_url(UuidBase64Url::from_bytes(bytes)))
}

fn parse_message_id(d: &mut impl Iterator<Item = u8>) -> Option<MessageId> {
    let bytes: Vec<u8> = d.by_ref().take(16).collect();
    let bytes = TryInto::<[u8; 16]>::try_into(bytes).ok()?;
    Some(MessageId::new(UuidBase64Url::from_bytes(bytes)))
}

#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    TryFromPrimitive,
    SimpleDieselEnum,
    diesel::FromSqlRow,
    diesel::AsExpression,
    Serialize,
    Deserialize,
    ToSchema,
)]
#[diesel(sql_type = SmallInt)]
#[repr(i16)]
pub enum DeliveryInfoType {
    Delivered = 0,
    DeliveryFailed = 1,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq)]
pub struct MessageDeliveryInfo {
    /// Database ID for the delivery info entry
    pub id: i64,
    /// Recipient of the message
    pub recipient: AccountId,
    /// Message UUID generated by sender
    pub message_id: MessageId,
    pub delivery_type: DeliveryInfoType,
    /// Unix time when the delivery info was created
    pub unix_time: UnixTime,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq, Default)]
pub struct MessageDeliveryInfoList {
    pub info: Vec<MessageDeliveryInfo>,
}

#[derive(Debug, Clone, Deserialize, Serialize, ToSchema, PartialEq, Default)]
pub struct MessageDeliveryInfoIdList {
    pub ids: Vec<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq)]
pub struct LatestSeenMessageInfo {
    /// Account which viewed/received the message
    pub viewer: AccountId,
    /// Latest message number seen by the viewer
    pub mn: MessageNumber,
    pub ut: UnixTime,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq, Default)]
pub struct LatestSeenMessageInfoList {
    pub info: Vec<LatestSeenMessageInfo>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq)]
pub struct DataExportMessageDeliveryInfo {
    pub id: i64,
    /// Sender of [Self::message_id]
    pub sender: AccountId,
    pub message_id: MessageId,
    pub delivery_type: DeliveryInfoType,
    pub unix_time: UnixTime,
}
