[package]
name = "server_state"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }

utoipa-axum = { workspace = true }

hyper = { workspace = true }

sha1 = { workspace = true }
base64 = { workspace = true }

error-stack = { workspace = true }
thiserror = { workspace = true }

config = { path = "../config" }
model = { path = "../model" }
model_server_data = { path = "../model_server_data" }
model_server_state = { path = "../model_server_state" }
model_chat = { path = "../model_chat" }

server_common = { path = "../server_common" }

utils = { path = "../utils" }
server_data = { path = "../server_data" }

simple_backend = { path = "../simple_backend" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_utils = { path = "../simple_backend_utils" }
manager_api = { path = "../manager_api" }
manager_model = { path = "../manager_model" }
