[package]
name = "server_state"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }

hyper = { workspace = true }
reqwest = { workspace = true }

error-stack = { workspace = true }
thiserror = { workspace = true }

config = { path = "../config" }
model = { path = "../model" }
model_account = { path = "../model_account" }
model_chat = { path = "../model_chat" }

server_common = { path = "../server_common" }

server_data = { path = "../server_data" }
server_data_chat = { path = "../server_data_chat" }
server_data_account = { path = "../server_data_account" }
server_data_profile = { path = "../server_data_profile" }

api_internal = { path = "../api_internal" }

simple_backend = { path = "../simple_backend" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_utils = { path = "../simple_backend_utils" }
