[package]
name = "server_state"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }

error-stack = { workspace = true }

config = { path = "../config" }
model = { path = "../model" }

server_common = { path = "../server_common" }

server_data = { path = "../server_data" }
server_data_all = { path = "../server_data_all" }
server_data_chat = { path = "../server_data_chat" }
server_data_account = { path = "../server_data_account" }
server_data_profile = { path = "../server_data_profile" }
server_data_media = { path = "../server_data_media" }

server_api = { path = "../server_api" }
server_api_media = { path = "../server_api_media" }

simple_backend = { path = "../simple_backend" }
simple_backend_config = { path = "../simple_backend_config" }
