[package]
name = "server_router_account"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { workspace = true, features = ["ws", "macros"] }

server_api = { path = "../server_api" }
server_api_account = { path = "../server_api_account" }

server_state = { path = "../server_state" }

simple_backend = { path = "../simple_backend" }
