[package]
name = "test_mode_tests_media"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory = { workspace = true }

test_mode_bot = { path = "../test_mode_bot" }
test_mode_tests = { path = "../test_mode_tests" }
