[package]
name = "server_common"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
rand = { workspace = true }
aes-gcm = { workspace = true }
base64 = { workspace = true }

tokio = { workspace = true }
tracing = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

# Push notifications
fcm = { workspace = true }
a2 = { workspace = true }
web-push = { workspace = true }

config = { path = "../config" }
database = { path = "../database" }
model = { path = "../model" }

simple_backend = { path = "../simple_backend" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_database = { path = "../simple_backend_database" }
