[package]
name = "server_common"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }

tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

async-trait = { workspace = true }

# Firebase cloud messaging
fcm = { workspace = true }

config = { path = "../config" }
database = { path = "../database" }
model = { path = "../model" }

simple_backend = { path = "../simple_backend" }
simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_database = { path = "../simple_backend_database" }
