[package]
name = "simple_backend_model"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { workspace = true, features = ["derive"] }
utoipa = { workspace = true, features = ["axum_extras", "uuid"] }
sqlx = { workspace = true, features = [ "runtime-tokio-rustls", "sqlite", "uuid" ] }
diesel = { workspace = true, features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }

simple_backend_utils = { path = "../simple_backend_utils"}
