[package]
name = "simple_backend_model"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { workspace = true }
utoipa = { workspace = true }
diesel = { workspace = true }

simple_backend_utils = { path = "../simple_backend_utils"}

[dev-dependencies]
uuid = { workspace = true }
