[package]
name = "test_mode_bot_runner"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { workspace = true }

tracing = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

async-trait = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }

simple_backend_utils = { path = "../simple_backend_utils" }
api_client = { path = "../api_client" }
utils = { path = "../utils" }
config = { path = "../config" }

test_mode_bot = { path = "../test_mode_bot" }
test_mode_utils = { path = "../test_mode_utils" }
