[package]
name = "test_mode_tests_runner"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }

num_cpus = { workspace = true }
inventory = { workspace = true }

config = { path = "../config" }
test_mode_utils = { path = "../test_mode_utils" }
test_mode_tests = { path = "../test_mode_tests" }
