[package]
name = "utils"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true }
rand = { workspace = true }
pgp = { workspace = true }
bstr = { workspace = true }
smallvec = { workspace = true }
