[package]
name = "server_data_media"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { workspace = true }

model = { path = "../model" }
model_media = { path = "../model_media" }
server_common = { path = "../server_common" }
server_data = { path = "../server_data" }

database = { path = "../database" }
database_media = { path = "../database_media" }
