[package]
name = "server_router_profile"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { workspace = true, features = ["ws", "macros"] }

server_api = { path = "../server_api" }
server_api_profile = { path = "../server_api_profile" }

server_state = { path = "../server_state" }
