[package]
name = "api_internal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde_json = { workspace = true }

model = { path = "../model" }
api_client = { path = "../api_client" }
