[package]
name = "simple_backend_utils"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { workspace = true }

chrono = { workspace = true }
serde = { workspace = true }
base64 = { workspace = true }
uuid = { workspace = true }
utoipa = { workspace = true }
