/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact:
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Capabilities {
    #[serde(rename = "admin_ban_profile", skip_serializing_if = "Option::is_none")]
    pub admin_ban_profile: Option<bool>,
    #[serde(rename = "admin_moderate_images", skip_serializing_if = "Option::is_none")]
    pub admin_moderate_images: Option<bool>,
    #[serde(rename = "admin_moderate_profiles", skip_serializing_if = "Option::is_none")]
    pub admin_moderate_profiles: Option<bool>,
    #[serde(rename = "admin_modify_capablities", skip_serializing_if = "Option::is_none")]
    pub admin_modify_capablities: Option<bool>,
    #[serde(rename = "admin_setup_possible", skip_serializing_if = "Option::is_none")]
    pub admin_setup_possible: Option<bool>,
    /// View public and private profiles.
    #[serde(rename = "admin_view_all_profiles", skip_serializing_if = "Option::is_none")]
    pub admin_view_all_profiles: Option<bool>,
    #[serde(rename = "admin_view_private_info", skip_serializing_if = "Option::is_none")]
    pub admin_view_private_info: Option<bool>,
    #[serde(rename = "admin_view_profile_history", skip_serializing_if = "Option::is_none")]
    pub admin_view_profile_history: Option<bool>,
    #[serde(rename = "banned_edit_profile", skip_serializing_if = "Option::is_none")]
    pub banned_edit_profile: Option<bool>,
    /// View public profiles
    #[serde(rename = "view_public_profiles", skip_serializing_if = "Option::is_none")]
    pub view_public_profiles: Option<bool>,
}

impl Capabilities {
    pub fn new() -> Capabilities {
        Capabilities {
            admin_ban_profile: None,
            admin_moderate_images: None,
            admin_moderate_profiles: None,
            admin_modify_capablities: None,
            admin_setup_possible: None,
            admin_view_all_profiles: None,
            admin_view_private_info: None,
            admin_view_profile_history: None,
            banned_edit_profile: None,
            view_public_profiles: None,
        }
    }
}
