/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModerationRequest {
    #[serde(rename = "account_id")]
    pub account_id: Box<crate::models::AccountIdLight>,
    #[serde(rename = "moderation_request_id")]
    pub moderation_request_id: uuid::Uuid,
    #[serde(rename = "queue_position")]
    pub queue_position: i64,
}

impl ModerationRequest {
    pub fn new(account_id: crate::models::AccountIdLight, moderation_request_id: uuid::Uuid, queue_position: i64) -> ModerationRequest {
        ModerationRequest {
            account_id: Box::new(account_id),
            moderation_request_id,
            queue_position,
        }
    }
}


