/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityImage {
    #[serde(rename = "content_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_id: Option<Option<Box<crate::models::ContentId>>>,
}

impl SecurityImage {
    pub fn new() -> SecurityImage {
        SecurityImage {
            content_id: None,
        }
    }
}


