[package]
name = "test_mode_utils"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
error-stack = { workspace = true }

tracing = { workspace = true }
reqwest = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }

nix = { workspace = true }
chrono = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }

simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend = { path = "../simple_backend" }
server_data = { path = "../server_data" }
api_client = { path = "../api_client" }
config = { path = "../config" }
