[package]
name = "server_router_chat"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { workspace = true }

server_api = { path = "../server_api" }
server_api_chat = { path = "../server_api_chat" }

server_state = { path = "../server_state" }
