[package]
name = "server_data"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["io"]}
axum = { workspace = true }
tracing = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

chrono = { workspace = true }

nalgebra = { workspace = true }

num_cpus = { workspace = true }

config = { path = "../config" }
database = { path = "../database" }
database_chat = { path = "../database_chat" }
model = { path = "../model" }
model_account = { path = "../model_account" }
server_common = { path = "../server_common" }

simple_backend = { path = "../simple_backend" }
simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_model = { path = "../simple_backend_model" }
