/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessibleAccount {
    #[serde(rename = "age", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub age: Option<Option<i64>>,
    #[serde(rename = "aid")]
    pub aid: Box<models::AccountId>,
    /// A string wrapper that ensures the string is not empty. This type is used for TEXT columns that should not allow empty strings. In the database, these columns are NULL when there is no value, and this type represents non-NULL values that must be non-empty.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl AccessibleAccount {
    pub fn new(aid: models::AccountId) -> AccessibleAccount {
        AccessibleAccount {
            age: None,
            aid: Box::new(aid),
            name: None,
        }
    }
}

