/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptedProfileAges {
    #[serde(rename = "profile_initial_age")]
    pub profile_initial_age: i64,
    #[serde(rename = "profile_initial_age_set_unix_time")]
    pub profile_initial_age_set_unix_time: Box<models::UnixTime>,
}

impl AcceptedProfileAges {
    pub fn new(profile_initial_age: i64, profile_initial_age_set_unix_time: models::UnixTime) -> AcceptedProfileAges {
        AcceptedProfileAges {
            profile_initial_age,
            profile_initial_age_set_unix_time: Box::new(profile_initial_age_set_unix_time),
        }
    }
}

