/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountVerificationScope {
    #[serde(rename = "profile_age_range", skip_serializing_if = "Option::is_none")]
    pub profile_age_range: Option<bool>,
    #[serde(rename = "profile_name", skip_serializing_if = "Option::is_none")]
    pub profile_name: Option<bool>,
    #[serde(rename = "security_content", skip_serializing_if = "Option::is_none")]
    pub security_content: Option<bool>,
}

impl AccountVerificationScope {
    pub fn new() -> AccountVerificationScope {
        AccountVerificationScope {
            profile_age_range: None,
            profile_name: None,
            security_content: None,
        }
    }
}

