/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminBotReportProcessingMessagesLlmConfig {
    /// If LLM response starts with this text or the first line of the response contains this text, the content is moderated as accepted. The comparisons are case insensitive.
    #[serde(rename = "expected_response")]
    pub expected_response: String,
    #[serde(rename = "system_text")]
    pub system_text: String,
    /// Placeholder \"{text}\" is replaced with the reported content.
    #[serde(rename = "user_text_template")]
    pub user_text_template: String,
    /// Placeholder \"{text}\" is replaced with the report creator's message.
    #[serde(rename = "report_creator_message_template")]
    pub report_creator_message_template: String,
    /// Placeholder \"{text}\" is replaced with the report target's message.
    #[serde(rename = "report_target_message_template")]
    pub report_target_message_template: String,
}

impl AdminBotReportProcessingMessagesLlmConfig {
    pub fn new(expected_response: String, system_text: String, user_text_template: String, report_creator_message_template: String, report_target_message_template: String) -> AdminBotReportProcessingMessagesLlmConfig {
        AdminBotReportProcessingMessagesLlmConfig {
            expected_response,
            system_text,
            user_text_template,
            report_creator_message_template,
            report_target_message_template,
        }
    }
}

