/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminBotReportProcessingProfileStringConfig {
    #[serde(rename = "automatic_banning_day_counts")]
    pub automatic_banning_day_counts: models::AutomaticBanningDayCountConfig,
    #[serde(rename = "automatic_banning_enabled", skip_serializing_if = "Option::is_none")]
    pub automatic_banning_enabled: Option<bool>,
    #[serde(rename = "default_action")]
    pub default_action: models::AcceptOrReject,
    #[serde(rename = "llm")]
    pub llm: models::AdminBotReportProcessingProfileStringLlmConfig,
    #[serde(rename = "llm_enabled", skip_serializing_if = "Option::is_none")]
    pub llm_enabled: Option<bool>,
}

impl AdminBotReportProcessingProfileStringConfig {
    pub fn new(automatic_banning_day_counts: models::AutomaticBanningDayCountConfig, default_action: models::AcceptOrReject, llm: models::AdminBotReportProcessingProfileStringLlmConfig) -> AdminBotReportProcessingProfileStringConfig {
        AdminBotReportProcessingProfileStringConfig {
            automatic_banning_day_counts,
            automatic_banning_enabled: None,
            default_action,
            llm,
            llm_enabled: None,
        }
    }
}

