/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgeVerificationConfig {
    #[serde(rename = "methods", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub methods: Option<Option<Box<models::AgeVerificationMethodsConfig>>>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<Box<models::AgeVerificationPlatforms>>,
    #[serde(rename = "verify_during_initial_setup", skip_serializing_if = "Option::is_none")]
    pub verify_during_initial_setup: Option<Box<models::AgeVerificationPlatforms>>,
}

impl AgeVerificationConfig {
    pub fn new() -> AgeVerificationConfig {
        AgeVerificationConfig {
            methods: None,
            required: None,
            verify_during_initial_setup: None,
        }
    }
}

