/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutomaticBanningConfig {
    #[serde(rename = "day_counts")]
    pub day_counts: models::AutomaticBanningDayCountConfig,
    /// Show ban reason details to the banned user.
    #[serde(rename = "reason_details_visible_to_user", skip_serializing_if = "Option::is_none")]
    pub reason_details_visible_to_user: Option<bool>,
    /// Save the LLM response as the ban reason details.
    #[serde(rename = "save_reason_details", skip_serializing_if = "Option::is_none")]
    pub save_reason_details: Option<bool>,
}

impl AutomaticBanningConfig {
    pub fn new(day_counts: models::AutomaticBanningDayCountConfig) -> AutomaticBanningConfig {
        AutomaticBanningConfig {
            day_counts,
            reason_details_visible_to_user: None,
            save_reason_details: None,
        }
    }
}

