/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutomaticBanningDayCountConfig {
    #[serde(rename = "high")]
    pub high: i32,
    #[serde(rename = "low")]
    pub low: i32,
    #[serde(rename = "medium")]
    pub medium: i32,
}

impl AutomaticBanningDayCountConfig {
    pub fn new(high: i32, low: i32, medium: i32) -> AutomaticBanningDayCountConfig {
        AutomaticBanningDayCountConfig {
            high,
            low,
            medium,
        }
    }
}

