/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BackupTransferClientRole {
    #[serde(rename = "Target")]
    Target,
    #[serde(rename = "Source")]
    Source,

}

impl std::fmt::Display for BackupTransferClientRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Target => write!(f, "Target"),
            Self::Source => write!(f, "Source"),
        }
    }
}

impl Default for BackupTransferClientRole {
    fn default() -> BackupTransferClientRole {
        Self::Target
    }
}

