/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BannerPlatform {
    #[serde(rename = "android", skip_serializing_if = "Option::is_none")]
    pub android: Option<bool>,
    #[serde(rename = "ios", skip_serializing_if = "Option::is_none")]
    pub ios: Option<bool>,
    #[serde(rename = "web", skip_serializing_if = "Option::is_none")]
    pub web: Option<bool>,
}

impl BannerPlatform {
    pub fn new() -> BannerPlatform {
        BannerPlatform {
            android: None,
            ios: None,
            web: None,
        }
    }
}

