/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BotConfig : Enable automatic bots when server starts. Editing of this field with edit module is only allowed when this exists in the config file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BotConfig {
    /// Admin bot count
    #[serde(rename = "admins")]
    pub admins: i32,
    /// User bot count
    #[serde(rename = "users")]
    pub users: i32,
}

impl BotConfig {
    /// Enable automatic bots when server starts. Editing of this field with edit module is only allowed when this exists in the config file.
    pub fn new(admins: i32, users: i32) -> BotConfig {
        BotConfig {
            admins,
            users,
        }
    }
}

