/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckOnlineStatusConfig {
    /// Client should wait at least this time before sending another check online status request.
    #[serde(rename = "min_wait_seconds_between_requests_client")]
    pub min_wait_seconds_between_requests_client: i32,
    /// Server ignores check online status requests that are received before wait time elapses.
    #[serde(rename = "min_wait_seconds_between_requests_server")]
    pub min_wait_seconds_between_requests_server: i32,
}

impl CheckOnlineStatusConfig {
    pub fn new(min_wait_seconds_between_requests_client: i32, min_wait_seconds_between_requests_server: i32) -> CheckOnlineStatusConfig {
        CheckOnlineStatusConfig {
            min_wait_seconds_between_requests_client,
            min_wait_seconds_between_requests_server,
        }
    }
}

