/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientMessageType : First byte of websocket binary protocol messages sent from client to server.  Remaining bytes are message payload. Payload format depends on the message type value: - `SyncVersionList` (0): payload contains list of current data sync versions.   Each byte in the payload is a sync version for a data type. The position   of the byte defines the data type (see `SyncCheckDataType`). If client   does not have any version of the data, version number must be `255`. - `ClearMaintenanceStatusIfPossible` (1): payload is empty. - `ResponseAdminBotConfigWarnings` (2): payload format:   - request id byte (u8)   - warnings flags byte (u8). Bits in the byte:     - bit 0: profile name moderation file config missing     - bit 1: profile text moderation file config missing     - bit 2: content moderation file config missing - `RequestResetProfilePaging` (60): payload format:   - request id byte (u8) - `RequestGetNextProfilePage` (61): payload format:   - request id byte (u8)   - profile iterator session id as minimal i64 - `RequestAutomaticProfileSearchResetProfilePaging` (62): payload format:   - request id byte (u8) - `RequestAutomaticProfileSearchGetNextProfilePage` (63): payload format:   - request id byte (u8)   - automatic profile search iterator session id as minimal i64 - `TypingStart` (120): payload is exactly 16 bytes account UUID in big-endian   byte order. - `TypingStop` (121): payload is empty. - `CheckOnlineStatus` (122): payload is 16 bytes account UUID. Optional   17th byte can be included for online status hint (0 = false, non-zero = true).  # Data formats  Data types used in payload definitions: - minimal i64:   - i64 byte count (u8, values: 1, 2, 4, 8)   - i64 bytes (little-endian byte order) - optional values in payloads are omitted when they are not present
/// First byte of websocket binary protocol messages sent from client to server.  Remaining bytes are message payload. Payload format depends on the message type value: - `SyncVersionList` (0): payload contains list of current data sync versions.   Each byte in the payload is a sync version for a data type. The position   of the byte defines the data type (see `SyncCheckDataType`). If client   does not have any version of the data, version number must be `255`. - `ClearMaintenanceStatusIfPossible` (1): payload is empty. - `ResponseAdminBotConfigWarnings` (2): payload format:   - request id byte (u8)   - warnings flags byte (u8). Bits in the byte:     - bit 0: profile name moderation file config missing     - bit 1: profile text moderation file config missing     - bit 2: content moderation file config missing - `RequestResetProfilePaging` (60): payload format:   - request id byte (u8) - `RequestGetNextProfilePage` (61): payload format:   - request id byte (u8)   - profile iterator session id as minimal i64 - `RequestAutomaticProfileSearchResetProfilePaging` (62): payload format:   - request id byte (u8) - `RequestAutomaticProfileSearchGetNextProfilePage` (63): payload format:   - request id byte (u8)   - automatic profile search iterator session id as minimal i64 - `TypingStart` (120): payload is exactly 16 bytes account UUID in big-endian   byte order. - `TypingStop` (121): payload is empty. - `CheckOnlineStatus` (122): payload is 16 bytes account UUID. Optional   17th byte can be included for online status hint (0 = false, non-zero = true).  # Data formats  Data types used in payload definitions: - minimal i64:   - i64 byte count (u8, values: 1, 2, 4, 8)   - i64 bytes (little-endian byte order) - optional values in payloads are omitted when they are not present
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientMessageType {
    #[serde(rename = "SyncVersionList")]
    SyncVersionList,
    #[serde(rename = "ClearMaintenanceStatusIfPossible")]
    ClearMaintenanceStatusIfPossible,
    #[serde(rename = "ResponseAdminBotConfigWarnings")]
    ResponseAdminBotConfigWarnings,
    #[serde(rename = "RequestResetProfilePaging")]
    RequestResetProfilePaging,
    #[serde(rename = "RequestGetNextProfilePage")]
    RequestGetNextProfilePage,
    #[serde(rename = "RequestAutomaticProfileSearchResetProfilePaging")]
    RequestAutomaticProfileSearchResetProfilePaging,
    #[serde(rename = "RequestAutomaticProfileSearchGetNextProfilePage")]
    RequestAutomaticProfileSearchGetNextProfilePage,
    #[serde(rename = "TypingStart")]
    TypingStart,
    #[serde(rename = "TypingStop")]
    TypingStop,
    #[serde(rename = "CheckOnlineStatus")]
    CheckOnlineStatus,

}

impl std::fmt::Display for ClientMessageType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SyncVersionList => write!(f, "SyncVersionList"),
            Self::ClearMaintenanceStatusIfPossible => write!(f, "ClearMaintenanceStatusIfPossible"),
            Self::ResponseAdminBotConfigWarnings => write!(f, "ResponseAdminBotConfigWarnings"),
            Self::RequestResetProfilePaging => write!(f, "RequestResetProfilePaging"),
            Self::RequestGetNextProfilePage => write!(f, "RequestGetNextProfilePage"),
            Self::RequestAutomaticProfileSearchResetProfilePaging => write!(f, "RequestAutomaticProfileSearchResetProfilePaging"),
            Self::RequestAutomaticProfileSearchGetNextProfilePage => write!(f, "RequestAutomaticProfileSearchGetNextProfilePage"),
            Self::TypingStart => write!(f, "TypingStart"),
            Self::TypingStop => write!(f, "TypingStop"),
            Self::CheckOnlineStatus => write!(f, "CheckOnlineStatus"),
        }
    }
}

impl Default for ClientMessageType {
    fn default() -> ClientMessageType {
        Self::SyncVersionList
    }
}

