/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientFeaturesConfig {
    #[serde(rename = "account_verification", skip_serializing_if = "Option::is_none")]
    pub account_verification: Option<models::AccountVerificationConfig>,
    #[serde(rename = "age_verification", skip_serializing_if = "Option::is_none")]
    pub age_verification: Option<models::AgeVerificationConfig>,
    #[serde(rename = "association", skip_serializing_if = "Option::is_none")]
    pub association: Option<models::AssociationConfig>,
    #[serde(rename = "attribution", skip_serializing_if = "Option::is_none")]
    pub attribution: Option<models::AttributionConfig>,
    #[serde(rename = "chat", skip_serializing_if = "Option::is_none")]
    pub chat: Option<models::ChatConfig>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<models::FeaturesConfig>,
    #[serde(rename = "likes", skip_serializing_if = "Option::is_none")]
    pub likes: Option<models::LikesConfig>,
    #[serde(rename = "map", skip_serializing_if = "Option::is_none")]
    pub map: Option<models::MapConfig>,
    #[serde(rename = "news", skip_serializing_if = "Option::is_none")]
    pub news: Option<models::NewsConfig>,
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<models::ProfileConfig>,
}

impl ClientFeaturesConfig {
    pub fn new() -> ClientFeaturesConfig {
        ClientFeaturesConfig {
            account_verification: None,
            age_verification: None,
            association: None,
            attribution: None,
            chat: None,
            features: None,
            likes: None,
            map: None,
            news: None,
            profile: None,
        }
    }
}

