/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientLocalId : ID which client owns. This should be unique when considering one client instance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientLocalId {
    #[serde(rename = "id")]
    pub id: i64,
}

impl ClientLocalId {
    /// ID which client owns. This should be unique when considering one client instance.
    pub fn new(id: i64) -> ClientLocalId {
        ClientLocalId {
            id,
        }
    }
}

