/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientInfo {
    #[serde(rename = "client_type")]
    pub client_type: models::ClientType,
    #[serde(rename = "major_version")]
    pub major_version: i32,
    #[serde(rename = "minor_version")]
    pub minor_version: i32,
    #[serde(rename = "patch_version")]
    pub patch_version: i32,
}

impl ClientInfo {
    pub fn new(client_type: models::ClientType, major_version: i32, minor_version: i32, patch_version: i32) -> ClientInfo {
        ClientInfo {
            client_type,
            major_version,
            minor_version,
            patch_version,
        }
    }
}

