/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientFeaturesConfigHash {
    #[serde(rename = "h")]
    pub h: String,
}

impl ClientFeaturesConfigHash {
    pub fn new(h: String) -> ClientFeaturesConfigHash {
        ClientFeaturesConfigHash {
            h,
        }
    }
}

