/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientMessageType : First byte of websocket binary protocol messages sent from client to server.  Remaining bytes are message payload. Payload format depends on the message type value: - `SyncVersionList` (0): payload contains list of current data sync versions.   Each byte in the payload is a sync version for a data type. The position   of the byte defines the data type (see `SyncCheckDataType`). If client   does not have any version of the data, version number must be `255`. - `ClearMaintenanceStatusIfPossible` (1): payload is empty. - `TypingStart` (120): payload is exactly 16 bytes account UUID in big-endian   byte order. - `TypingStop` (121): payload is empty. - `CheckOnlineStatus` (122): payload is 16 bytes account UUID. Optional 17th   byte can be included for online status hint (0 = false, non-zero = true).
/// First byte of websocket binary protocol messages sent from client to server.  Remaining bytes are message payload. Payload format depends on the message type value: - `SyncVersionList` (0): payload contains list of current data sync versions.   Each byte in the payload is a sync version for a data type. The position   of the byte defines the data type (see `SyncCheckDataType`). If client   does not have any version of the data, version number must be `255`. - `ClearMaintenanceStatusIfPossible` (1): payload is empty. - `TypingStart` (120): payload is exactly 16 bytes account UUID in big-endian   byte order. - `TypingStop` (121): payload is empty. - `CheckOnlineStatus` (122): payload is 16 bytes account UUID. Optional 17th   byte can be included for online status hint (0 = false, non-zero = true).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClientMessageType {
    #[serde(rename = "SyncVersionList")]
    SyncVersionList,
    #[serde(rename = "ClearMaintenanceStatusIfPossible")]
    ClearMaintenanceStatusIfPossible,
    #[serde(rename = "TypingStart")]
    TypingStart,
    #[serde(rename = "TypingStop")]
    TypingStop,
    #[serde(rename = "CheckOnlineStatus")]
    CheckOnlineStatus,

}

impl std::fmt::Display for ClientMessageType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SyncVersionList => write!(f, "SyncVersionList"),
            Self::ClearMaintenanceStatusIfPossible => write!(f, "ClearMaintenanceStatusIfPossible"),
            Self::TypingStart => write!(f, "TypingStart"),
            Self::TypingStop => write!(f, "TypingStop"),
            Self::CheckOnlineStatus => write!(f, "CheckOnlineStatus"),
        }
    }
}

impl Default for ClientMessageType {
    fn default() -> ClientMessageType {
        Self::SyncVersionList
    }
}

