/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectionStatistics : WebSocket connection statistics for 24 hours.  All lists contain 24 values starting from UTC time 00:00.  Bots are not included in this data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionStatistics {
    #[serde(rename = "all")]
    pub all: Vec<i32>,
    #[serde(rename = "men")]
    pub men: Vec<i32>,
    #[serde(rename = "nonbinaries")]
    pub nonbinaries: Vec<i32>,
    #[serde(rename = "women")]
    pub women: Vec<i32>,
}

impl ConnectionStatistics {
    /// WebSocket connection statistics for 24 hours.  All lists contain 24 values starting from UTC time 00:00.  Bots are not included in this data.
    pub fn new(all: Vec<i32>, men: Vec<i32>, nonbinaries: Vec<i32>, women: Vec<i32>) -> ConnectionStatistics {
        ConnectionStatistics {
            all,
            men,
            nonbinaries,
            women,
        }
    }
}

