/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentInfoWithFd {
    #[serde(rename = "cid")]
    pub cid: Box<models::ContentId>,
    #[serde(rename = "ctype")]
    pub ctype: models::MediaContentType,
    /// Face detected
    #[serde(rename = "fd")]
    pub fd: bool,
    #[serde(rename = "rejected_reason_category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejected_reason_category: Option<Option<Box<models::ProfileContentModerationRejectedReasonCategory>>>,
    #[serde(rename = "rejected_reason_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejected_reason_details: Option<Option<Box<models::ProfileContentModerationRejectedReasonDetails>>>,
    #[serde(rename = "state")]
    pub state: models::ContentModerationState,
}

impl ContentInfoWithFd {
    pub fn new(cid: models::ContentId, ctype: models::MediaContentType, fd: bool, state: models::ContentModerationState) -> ContentInfoWithFd {
        ContentInfoWithFd {
            cid: Box::new(cid),
            ctype,
            fd,
            rejected_reason_category: None,
            rejected_reason_details: None,
            state,
        }
    }
}

