/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentInfoDetailed {
    #[serde(rename = "cid")]
    pub cid: Box<models::ContentId>,
    #[serde(rename = "ctype")]
    pub ctype: models::MediaContentType,
    /// Face detected
    #[serde(rename = "fd")]
    pub fd: bool,
    #[serde(rename = "secure_capture")]
    pub secure_capture: bool,
    #[serde(rename = "slot", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub slot: Option<Option<models::ContentSlot>>,
    #[serde(rename = "state")]
    pub state: models::ContentModerationState,
    #[serde(rename = "usage_end_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub usage_end_time: Option<Option<Box<models::UnixTime>>>,
    #[serde(rename = "usage_start_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub usage_start_time: Option<Option<Box<models::UnixTime>>>,
}

impl ContentInfoDetailed {
    pub fn new(cid: models::ContentId, ctype: models::MediaContentType, fd: bool, secure_capture: bool, state: models::ContentModerationState) -> ContentInfoDetailed {
        ContentInfoDetailed {
            cid: Box::new(cid),
            ctype,
            fd,
            secure_capture,
            slot: None,
            state,
            usage_end_time: None,
            usage_start_time: None,
        }
    }
}

