/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentInfo {
    #[serde(rename = "cid")]
    pub cid: Box<models::ContentId>,
    #[serde(rename = "ctype")]
    pub ctype: models::MediaContentType,
    /// Face detected
    #[serde(rename = "fd")]
    pub fd: bool,
}

impl ContentInfo {
    pub fn new(cid: models::ContentId, ctype: models::MediaContentType, fd: bool) -> ContentInfo {
        ContentInfo {
            cid: Box::new(cid),
            ctype,
            fd,
        }
    }
}

