/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomReportContent {
    #[serde(rename = "boolean_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub boolean_value: Option<Option<bool>>,
}

impl CustomReportContent {
    pub fn new() -> CustomReportContent {
        CustomReportContent {
            boolean_value: None,
        }
    }
}

