/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomReportLanguage {
    /// Language code.
    #[serde(rename = "lang")]
    pub lang: String,
    #[serde(rename = "values")]
    pub values: Vec<models::CustomReportTranslation>,
}

impl CustomReportLanguage {
    pub fn new(lang: String, values: Vec<models::CustomReportTranslation>) -> CustomReportLanguage {
        CustomReportLanguage {
            lang,
            values,
        }
    }
}

