/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DailyLikesConfig {
    #[serde(rename = "daily_likes")]
    pub daily_likes: i32,
    /// UTC time value
    #[serde(rename = "reset_time")]
    pub reset_time: String,
}

impl DailyLikesConfig {
    pub fn new(daily_likes: i32, reset_time: String) -> DailyLikesConfig {
        DailyLikesConfig {
            daily_likes,
            reset_time,
        }
    }
}

