/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeliveryInfoType {
    #[serde(rename = "Delivered")]
    Delivered,
    #[serde(rename = "DeliveryFailed")]
    DeliveryFailed,

}

impl std::fmt::Display for DeliveryInfoType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Delivered => write!(f, "Delivered"),
            Self::DeliveryFailed => write!(f, "DeliveryFailed"),
        }
    }
}

impl Default for DeliveryInfoType {
    fn default() -> DeliveryInfoType {
        Self::Delivered
    }
}

