/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditVerificationValues {
    #[serde(rename = "profile_age_range", skip_serializing_if = "Option::is_none")]
    pub profile_age_range: Option<models::EditVerificationProfileAgeRange>,
    #[serde(rename = "profile_name", skip_serializing_if = "Option::is_none")]
    pub profile_name: Option<models::EditVerificationProfileName>,
    #[serde(rename = "security_content", skip_serializing_if = "Option::is_none")]
    pub security_content: Option<models::EditVerificationSecurityContent>,
}

impl EditVerificationValues {
    pub fn new() -> EditVerificationValues {
        EditVerificationValues {
            profile_age_range: None,
            profile_name: None,
            security_content: None,
        }
    }
}

