/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailAddressStateAdmin {
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "email_change", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_change: Option<Option<String>>,
    #[serde(rename = "email_change_verified", skip_serializing_if = "Option::is_none")]
    pub email_change_verified: Option<bool>,
    #[serde(rename = "email_login_enabled", skip_serializing_if = "Option::is_none")]
    pub email_login_enabled: Option<bool>,
}

impl EmailAddressStateAdmin {
    pub fn new() -> EmailAddressStateAdmin {
        EmailAddressStateAdmin {
            email: None,
            email_change: None,
            email_change_verified: None,
            email_login_enabled: None,
        }
    }
}

