/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmailLoginToken : Email login token is a 128 bit token used for email-based authentication where client receives one token via API and another is sent via email.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailLoginToken {
    /// Base64 URL safe without padding
    #[serde(rename = "token")]
    pub token: String,
}

impl EmailLoginToken {
    /// Email login token is a 128 bit token used for email-based authentication where client receives one token via API and another is sent via email.
    pub fn new(token: String) -> EmailLoginToken {
        EmailLoginToken {
            token,
        }
    }
}

