/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailRegistrationDomainLists {
    /// If non-empty, only email domains in this list are accepted for email registration. Values are lowercased and trimmed when the config is saved.
    #[serde(rename = "allowlist", skip_serializing_if = "Option::is_none")]
    pub allowlist: Option<Vec<String>>,
    /// Email domains in this list are rejected for email registration. Values are lowercased and trimmed when the config is saved.
    #[serde(rename = "blocklist", skip_serializing_if = "Option::is_none")]
    pub blocklist: Option<Vec<String>>,
}

impl EmailRegistrationDomainLists {
    pub fn new() -> EmailRegistrationDomainLists {
        EmailRegistrationDomainLists {
            allowlist: None,
            blocklist: None,
        }
    }
}

