/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventToClient : Event to client which is sent through websocket.  This is not an enum to make generated API bindings more easier to use.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventToClient {
    /// Data for event ContentProcessingStateChanged
    #[serde(rename = "content_processing_state_changed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_processing_state_changed: Option<Option<Box<models::ContentProcessingStateChanged>>>,
    #[serde(rename = "event")]
    pub event: models::EventType,
    /// Data for event LatestViewedMessageChanged
    #[serde(rename = "latest_viewed_message_changed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latest_viewed_message_changed: Option<Option<Box<models::LatestViewedMessageChanged>>>,
    /// Data for event ScheduledMaintenanceStatus
    #[serde(rename = "scheduled_maintenance_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scheduled_maintenance_status: Option<Option<Box<models::ScheduledMaintenanceStatus>>>,
}

impl EventToClient {
    /// Event to client which is sent through websocket.  This is not an enum to make generated API bindings more easier to use.
    pub fn new(event: models::EventType) -> EventToClient {
        EventToClient {
            content_processing_state_changed: None,
            event,
            latest_viewed_message_changed: None,
            scheduled_maintenance_status: None,
        }
    }
}

