/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetChatMessageReports {
    #[serde(rename = "creator")]
    pub creator: Box<models::AccountId>,
    #[serde(rename = "only_not_processed")]
    pub only_not_processed: bool,
    #[serde(rename = "target")]
    pub target: Box<models::AccountId>,
}

impl GetChatMessageReports {
    pub fn new(creator: models::AccountId, only_not_processed: bool, target: models::AccountId) -> GetChatMessageReports {
        GetChatMessageReports {
            creator: Box::new(creator),
            only_not_processed,
            target: Box::new(target),
        }
    }
}

