/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProfileAgeAndName {
    #[serde(rename = "age")]
    pub age: i64,
    #[serde(rename = "name")]
    pub name: String,
}

impl GetProfileAgeAndName {
    pub fn new(age: i64, name: String) -> GetProfileAgeAndName {
        GetProfileAgeAndName {
            age,
            name,
        }
    }
}

