/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWaitingReportsPage {
    /// Wanted report types. Empty list means all report types.
    #[serde(rename = "wanted_report_types", skip_serializing_if = "Option::is_none")]
    pub wanted_report_types: Option<Vec<models::ReportType>>,
}

impl GetWaitingReportsPage {
    pub fn new() -> GetWaitingReportsPage {
        GetWaitingReportsPage {
            wanted_report_types: None,
        }
    }
}

