/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContentQueryParams {
    /// If false media content access is allowed when profile is set as public. If true media content access is allowed when users are a match.
    #[serde(rename = "is_match", skip_serializing_if = "Option::is_none")]
    pub is_match: Option<bool>,
}

impl GetContentQueryParams {
    pub fn new() -> GetContentQueryParams {
        GetContentQueryParams {
            is_match: None,
        }
    }
}

