/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageProcessingDynamicConfig {
    /// Thresholds when an image is classified as NSFW.  If a probability value is equal or greater than the related threshold then the image is classified as NSFW.  Threshold values must be in the range 0.0–1.0.
    #[serde(rename = "nsfw_thresholds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nsfw_thresholds: Option<Option<Box<models::NsfwDetectionThresholds>>>,
    /// See [rustface::Detector::set_score_thresh] documentation. Value 1.0 seems to work well.
    #[serde(rename = "seetaface_threshold", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seetaface_threshold: Option<Option<f64>>,
}

impl ImageProcessingDynamicConfig {
    pub fn new() -> ImageProcessingDynamicConfig {
        ImageProcessingDynamicConfig {
            nsfw_thresholds: None,
            seetaface_threshold: None,
        }
    }
}

