/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpCountryStatisticsValue {
    #[serde(rename = "c")]
    pub c: i64,
    /// Value exists when [GetIpCountryStatisticsSettings::live_statistics] is false.
    #[serde(rename = "t", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub t: Option<Option<Box<models::UnixTime>>>,
}

impl IpCountryStatisticsValue {
    pub fn new(c: i64) -> IpCountryStatisticsValue {
        IpCountryStatisticsValue {
            c,
            t: None,
        }
    }
}

