/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatestSeenMessageInfoList {
    #[serde(rename = "info")]
    pub info: Vec<models::LatestSeenMessageInfo>,
}

impl LatestSeenMessageInfoList {
    pub fn new(info: Vec<models::LatestSeenMessageInfo>) -> LatestSeenMessageInfoList {
        LatestSeenMessageInfoList {
            info,
        }
    }
}

