/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LikeSendingLimitConfig {
    #[serde(rename = "daily_limit")]
    pub daily_limit: i32,
    /// UTC time value
    #[serde(rename = "reset_time")]
    pub reset_time: String,
}

impl LikeSendingLimitConfig {
    pub fn new(daily_limit: i32, reset_time: String) -> LikeSendingLimitConfig {
        LikeSendingLimitConfig {
            daily_limit,
            reset_time,
        }
    }
}

