/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaintenanceTask {
    #[serde(rename = "notify_backend")]
    pub notify_backend: bool,
    #[serde(rename = "time")]
    pub time: Box<models::UnixTime>,
}

impl MaintenanceTask {
    pub fn new(notify_backend: bool, time: models::UnixTime) -> MaintenanceTask {
        MaintenanceTask {
            notify_backend,
            time: Box::new(time),
        }
    }
}

