/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchesPage {
    #[serde(rename = "error_invalid_iterator_session_id", skip_serializing_if = "Option::is_none")]
    pub error_invalid_iterator_session_id: Option<bool>,
    #[serde(rename = "p")]
    pub p: Vec<models::AccountId>,
}

impl MatchesPage {
    pub fn new(p: Vec<models::AccountId>) -> MatchesPage {
        MatchesPage {
            error_invalid_iterator_session_id: None,
            p,
        }
    }
}

