/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaContentPendingModeration {
    #[serde(rename = "account_id")]
    pub account_id: Box<models::AccountId>,
    #[serde(rename = "content_id")]
    pub content_id: Box<models::ContentId>,
    #[serde(rename = "rejected_category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejected_category: Option<Option<Box<models::MediaContentModerationRejectedReasonCategory>>>,
    #[serde(rename = "rejected_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejected_details: Option<Option<Box<models::MediaContentModerationRejectedReasonDetails>>>,
}

impl MediaContentPendingModeration {
    pub fn new(account_id: models::AccountId, content_id: models::ContentId) -> MediaContentPendingModeration {
        MediaContentPendingModeration {
            account_id: Box::new(account_id),
            content_id: Box::new(content_id),
            rejected_category: None,
            rejected_details: None,
        }
    }
}

