/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MessageNumber : Message number for identifying a message in a conversation.  The number is conversation specific and it increments.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageNumber {
    #[serde(rename = "mn")]
    pub mn: i64,
}

impl MessageNumber {
    /// Message number for identifying a message in a conversation.  The number is conversation specific and it increments.
    pub fn new(mn: i64) -> MessageNumber {
        MessageNumber {
            mn,
        }
    }
}

