/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewMessageNotification {
    #[serde(rename = "a")]
    pub a: Box<models::AccountId>,
    #[serde(rename = "c")]
    pub c: Box<models::ConversationId>,
    /// Message count
    #[serde(rename = "m")]
    pub m: i64,
}

impl NewMessageNotification {
    pub fn new(a: models::AccountId, c: models::ConversationId, m: i64) -> NewMessageNotification {
        NewMessageNotification {
            a: Box::new(a),
            c: Box::new(c),
            m,
        }
    }
}

