/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewsConfig {
    /// Make possible for admins to write translations for news. If news translation is not available then server returns news with locale \"default\".
    #[serde(rename = "locales")]
    pub locales: Vec<String>,
}

impl NewsConfig {
    pub fn new(locales: Vec<String>) -> NewsConfig {
        NewsConfig {
            locales,
        }
    }
}

