/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationId : Notification ID for an event. Can be used to prevent showing the same notification again. The ID is i8 number which will wrap.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationId {
    #[serde(rename = "id")]
    pub id: i32,
}

impl NotificationId {
    /// Notification ID for an event. Can be used to prevent showing the same notification again. The ID is i8 number which will wrap.
    pub fn new(id: i32) -> NotificationId {
        NotificationId {
            id,
        }
    }
}

