/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationStatus {
    #[serde(rename = "id")]
    pub id: Box<models::NotificationId>,
    #[serde(rename = "viewed")]
    pub viewed: Box<models::NotificationIdViewed>,
}

impl NotificationStatus {
    pub fn new(id: models::NotificationId, viewed: models::NotificationIdViewed) -> NotificationStatus {
        NotificationStatus {
            id: Box::new(id),
            viewed: Box::new(viewed),
        }
    }
}

