/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PageItemCountForNewLikes : Define how many returned profiles counted from the first page item are new likes (interaction state changed to like after previous received likes iterator reset).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageItemCountForNewLikes {
    #[serde(rename = "c")]
    pub c: i64,
}

impl PageItemCountForNewLikes {
    /// Define how many returned profiles counted from the first page item are new likes (interaction state changed to like after previous received likes iterator reset).
    pub fn new(c: i64) -> PageItemCountForNewLikes {
        PageItemCountForNewLikes {
            c,
        }
    }
}

