/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingChatNotificationToDelete {
    #[serde(rename = "account_id_sender")]
    pub account_id_sender: Box<models::AccountId>,
    #[serde(rename = "message_count")]
    pub message_count: i64,
}

impl PendingChatNotificationToDelete {
    pub fn new(account_id_sender: models::AccountId, message_count: i64) -> PendingChatNotificationToDelete {
        PendingChatNotificationToDelete {
            account_id_sender: Box::new(account_id_sender),
            message_count,
        }
    }
}

