/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingMessageAcknowledgementList {
    #[serde(rename = "delivery_failed", skip_serializing_if = "Option::is_none")]
    pub delivery_failed: Option<bool>,
    #[serde(rename = "ids")]
    pub ids: Vec<models::PendingMessageId>,
}

impl PendingMessageAcknowledgementList {
    pub fn new(ids: Vec<models::PendingMessageId>) -> PendingMessageAcknowledgementList {
        PendingMessageAcknowledgementList {
            delivery_failed: None,
            ids,
        }
    }
}

