/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostProfileAgeRangeVerifiedValue {
    #[serde(rename = "account_id")]
    pub account_id: Box<models::AccountId>,
    /// Bot sets automatic profile age range verification value. Human admin sets manual override value. Set to None to clear the currently applicable value.
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<bool>>,
}

impl PostProfileAgeRangeVerifiedValue {
    pub fn new(account_id: models::AccountId) -> PostProfileAgeRangeVerifiedValue {
        PostProfileAgeRangeVerifiedValue {
            account_id: Box::new(account_id),
            value: None,
        }
    }
}

