/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostStartDataExport {
    #[serde(rename = "data_export_type")]
    pub data_export_type: models::DataExportType,
    /// Data reading source account.
    #[serde(rename = "source")]
    pub source: Box<models::AccountId>,
}

impl PostStartDataExport {
    pub fn new(data_export_type: models::DataExportType, source: models::AccountId) -> PostStartDataExport {
        PostStartDataExport {
            data_export_type,
            source: Box::new(source),
        }
    }
}

