/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSecurityContentVerificationQueueRemoveNextItem {
    #[serde(rename = "account_id")]
    pub account_id: Box<models::AccountId>,
}

impl PostSecurityContentVerificationQueueRemoveNextItem {
    pub fn new(account_id: models::AccountId) -> PostSecurityContentVerificationQueueRemoveNextItem {
        PostSecurityContentVerificationQueueRemoveNextItem {
            account_id: Box::new(account_id),
        }
    }
}

