/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessReport {
    #[serde(rename = "content")]
    pub content: Box<models::ReportContent>,
    #[serde(rename = "creator")]
    pub creator: Box<models::AccountId>,
    #[serde(rename = "report_type")]
    pub report_type: Box<models::ReportTypeNumber>,
    #[serde(rename = "target")]
    pub target: Box<models::AccountId>,
}

impl ProcessReport {
    pub fn new(content: models::ReportContent, creator: models::AccountId, report_type: models::ReportTypeNumber, target: models::AccountId) -> ProcessReport {
        ProcessReport {
            content: Box::new(content),
            creator: Box::new(creator),
            report_type: Box::new(report_type),
            target: Box::new(target),
        }
    }
}

