/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileAttributeValue {
    #[serde(rename = "id")]
    pub id: i32,
    /// For bitflag filters the list only has one u16 value.  For one level attributes the values are u16 attribute value IDs.  For two level attributes the values are u32 values with most significant u16 containing attribute value ID and least significant u16 containing group value ID.  Values are in ascending order.
    #[serde(rename = "v")]
    pub v: Vec<i32>,
}

impl ProfileAttributeValue {
    pub fn new(id: i32, v: Vec<i32>) -> ProfileAttributeValue {
        ProfileAttributeValue {
            id,
            v,
        }
    }
}

