/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileUpdate {
    #[serde(rename = "age")]
    pub age: i64,
    #[serde(rename = "attributes")]
    pub attributes: Vec<models::ProfileAttributeValueUpdate>,
    #[serde(rename = "name")]
    pub name: String,
    /// This must be empty because profile text support is disabled.
    #[serde(rename = "ptext")]
    pub ptext: String,
}

impl ProfileUpdate {
    pub fn new(age: i64, attributes: Vec<models::ProfileAttributeValueUpdate>, name: String, ptext: String) -> ProfileUpdate {
        ProfileUpdate {
            age,
            attributes,
            name,
            ptext,
        }
    }
}

