/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileAttributeFilterListUpdate {
    #[serde(rename = "filters")]
    pub filters: Vec<crate::models::ProfileAttributeFilterValueUpdate>,
    #[serde(rename = "last_seen_time_filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_seen_time_filter: Option<Option<Box<crate::models::LastSeenTimeFilter>>>,
    #[serde(rename = "unlimited_likes_filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unlimited_likes_filter: Option<Option<bool>>,
}

impl ProfileAttributeFilterListUpdate {
    pub fn new(filters: Vec<crate::models::ProfileAttributeFilterValueUpdate>) -> ProfileAttributeFilterListUpdate {
        ProfileAttributeFilterListUpdate {
            filters,
            last_seen_time_filter: None,
            unlimited_likes_filter: None,
        }
    }
}


