/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileAgeCounts {
    #[serde(rename = "man")]
    pub man: Vec<i64>,
    #[serde(rename = "non_binary")]
    pub non_binary: Vec<i64>,
    /// Age for first count
    #[serde(rename = "start_age")]
    pub start_age: i64,
    #[serde(rename = "woman")]
    pub woman: Vec<i64>,
}

impl ProfileAgeCounts {
    pub fn new(man: Vec<i64>, non_binary: Vec<i64>, start_age: i64, woman: Vec<i64>) -> ProfileAgeCounts {
        ProfileAgeCounts {
            man,
            non_binary,
            start_age,
            woman,
        }
    }
}

