/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProfileStringModerationQueueType {
    #[serde(rename = "WaitingAdminBot")]
    WaitingAdminBot,
    #[serde(rename = "WaitingAdmin")]
    WaitingAdmin,
    #[serde(rename = "ProcessedByAdminBot")]
    ProcessedByAdminBot,

}

impl std::fmt::Display for ProfileStringModerationQueueType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WaitingAdminBot => write!(f, "WaitingAdminBot"),
            Self::WaitingAdmin => write!(f, "WaitingAdmin"),
            Self::ProcessedByAdminBot => write!(f, "ProcessedByAdminBot"),
        }
    }
}

impl Default for ProfileStringModerationQueueType {
    fn default() -> ProfileStringModerationQueueType {
        Self::WaitingAdminBot
    }
}

