/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileAttributeInfo {
    #[serde(rename = "attribute_order")]
    pub attribute_order: models::AttributeOrderMode,
    #[serde(rename = "attributes")]
    pub attributes: Vec<models::AttributeIdAndHash>,
}

impl ProfileAttributeInfo {
    pub fn new(attribute_order: models::AttributeOrderMode, attributes: Vec<models::AttributeIdAndHash>) -> ProfileAttributeInfo {
        ProfileAttributeInfo {
            attribute_order,
            attributes,
        }
    }
}

