/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfilePage {
    #[serde(rename = "error_invalid_iterator_session_id", skip_serializing_if = "Option::is_none")]
    pub error_invalid_iterator_session_id: Option<bool>,
    #[serde(rename = "profiles")]
    pub profiles: Vec<crate::models::ProfileLink>,
}

impl ProfilePage {
    pub fn new(profiles: Vec<crate::models::ProfileLink>) -> ProfilePage {
        ProfilePage {
            error_invalid_iterator_session_id: None,
            profiles,
        }
    }
}


