/*
 * dating-app-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileIteratorPageValue {
    #[serde(rename = "account_id")]
    pub account_id: Box<models::AccountId>,
    #[serde(rename = "age")]
    pub age: i64,
    #[serde(rename = "name")]
    pub name: String,
}

impl ProfileIteratorPageValue {
    pub fn new(account_id: models::AccountId, age: i64, name: String) -> ProfileIteratorPageValue {
        ProfileIteratorPageValue {
            account_id: Box::new(account_id),
            age,
            name,
        }
    }
}

