/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfileUpdate {
    #[serde(rename = "profile_text")]
    pub profile_text: String,
}

impl ProfileUpdate {
    pub fn new(profile_text: String) -> ProfileUpdate {
        ProfileUpdate {
            profile_text,
        }
    }
}


