/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileLink {
    #[serde(rename = "a")]
    pub a: Box<models::AccountId>,
    #[serde(rename = "c")]
    pub c: Box<models::ProfileContentVersion>,
    /// Account's most recent disconnect time.  If the last seen time is not None, then it is Unix timestamp or -1 if the profile is currently online.
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<i64>,
    #[serde(rename = "p")]
    pub p: Box<models::ProfileVersion>,
}

impl ProfileLink {
    pub fn new(a: models::AccountId, c: models::ProfileContentVersion, p: models::ProfileVersion) -> ProfileLink {
        ProfileLink {
            a: Box::new(a),
            c: Box::new(c),
            l: None,
            p: Box::new(p),
        }
    }
}

