/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProfileTextMaxCharactersFilter : Filter value for profile text max characters. The value must be 0 or greater.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileTextMaxCharactersFilter {
    #[serde(rename = "value")]
    pub value: i32,
}

impl ProfileTextMaxCharactersFilter {
    /// Filter value for profile text max characters. The value must be 0 or greater.
    pub fn new(value: i32) -> ProfileTextMaxCharactersFilter {
        ProfileTextMaxCharactersFilter {
            value,
        }
    }
}

