/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PushNotificationEncryptionKey : 128 bit random value which is Base64 encoded.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushNotificationEncryptionKey {
    #[serde(rename = "key")]
    pub key: String,
}

impl PushNotificationEncryptionKey {
    /// 128 bit random value which is Base64 encoded.
    pub fn new(key: String) -> PushNotificationEncryptionKey {
        PushNotificationEncryptionKey {
            key,
        }
    }
}

