/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReceivedLikesPage {
    #[serde(rename = "profiles")]
    pub profiles: Vec<crate::models::AccountId>,
    #[serde(rename = "version")]
    pub version: Box<crate::models::ReceivedLikesSyncVersion>,
}

impl ReceivedLikesPage {
    pub fn new(profiles: Vec<crate::models::AccountId>, version: crate::models::ReceivedLikesSyncVersion) -> ReceivedLikesPage {
        ReceivedLikesPage {
            profiles,
            version: Box::new(version),
        }
    }
}


