/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceivedLikesPageItem {
    /// If Some, the like is not viewed yet
    #[serde(rename = "not_viewed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub not_viewed: Option<Option<Box<models::ReceivedLikeId>>>,
    #[serde(rename = "p")]
    pub p: Box<models::ProfileLink>,
}

impl ReceivedLikesPageItem {
    pub fn new(p: models::ProfileLink) -> ReceivedLikesPageItem {
        ReceivedLikesPageItem {
            not_viewed: None,
            p: Box::new(p),
        }
    }
}

