/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceivedLikesIteratorState {
    #[serde(rename = "id_at_reset")]
    pub id_at_reset: Box<models::ReceivedLikeId>,
    #[serde(rename = "page")]
    pub page: i64,
    #[serde(rename = "previous_id_at_reset", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub previous_id_at_reset: Option<Option<Box<models::ReceivedLikeId>>>,
}

impl ReceivedLikesIteratorState {
    pub fn new(id_at_reset: models::ReceivedLikeId, page: i64) -> ReceivedLikesIteratorState {
        ReceivedLikesIteratorState {
            id_at_reset: Box::new(id_at_reset),
            page,
            previous_id_at_reset: None,
        }
    }
}

