/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportProcessingState {
    #[serde(rename = "Waiting")]
    Waiting,
    #[serde(rename = "ValidByAdminBot")]
    ValidByAdminBot,
    #[serde(rename = "ValidByAdmin")]
    ValidByAdmin,
    #[serde(rename = "InvalidByAdminBot")]
    InvalidByAdminBot,
    #[serde(rename = "InvalidByAdmin")]
    InvalidByAdmin,

}

impl std::fmt::Display for ReportProcessingState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Waiting => write!(f, "Waiting"),
            Self::ValidByAdminBot => write!(f, "ValidByAdminBot"),
            Self::ValidByAdmin => write!(f, "ValidByAdmin"),
            Self::InvalidByAdminBot => write!(f, "InvalidByAdminBot"),
            Self::InvalidByAdmin => write!(f, "InvalidByAdmin"),
        }
    }
}

impl Default for ReportProcessingState {
    fn default() -> ReportProcessingState {
        Self::Waiting
    }
}

