/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportContent {
    #[serde(rename = "chat_message", skip_serializing_if = "Option::is_none")]
    pub chat_message: Option<models::ChatMessageReport>,
    #[serde(rename = "profile_content", skip_serializing_if = "Option::is_none")]
    pub profile_content: Option<models::ContentId>,
    /// Null or non-empty string
    #[serde(rename = "profile_name", skip_serializing_if = "Option::is_none")]
    pub profile_name: Option<String>,
    /// Null or non-empty string
    #[serde(rename = "profile_text", skip_serializing_if = "Option::is_none")]
    pub profile_text: Option<String>,
}

impl ReportContent {
    pub fn new() -> ReportContent {
        ReportContent {
            chat_message: None,
            profile_content: None,
            profile_name: None,
            profile_text: None,
        }
    }
}

