/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportProcessingState {
    #[serde(rename = "Empty")]
    Empty,
    #[serde(rename = "Waiting")]
    Waiting,
    #[serde(rename = "Done")]
    Done,

}

impl std::fmt::Display for ReportProcessingState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Empty => write!(f, "Empty"),
            Self::Waiting => write!(f, "Waiting"),
            Self::Done => write!(f, "Done"),
        }
    }
}

impl Default for ReportProcessingState {
    fn default() -> ReportProcessingState {
        Self::Empty
    }
}

