/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportDetailed {
    /// Only available when account interaction exists.
    #[serde(rename = "chat_info", skip_serializing_if = "Option::is_none")]
    pub chat_info: Option<models::ReportChatInfo>,
    #[serde(rename = "content")]
    pub content: models::ReportContent,
    #[serde(rename = "creator_info")]
    pub creator_info: models::ReportAccountInfo,
    #[serde(rename = "info")]
    pub info: models::ReportDetailedInfo,
    #[serde(rename = "target_info")]
    pub target_info: models::ReportAccountInfo,
}

impl ReportDetailed {
    pub fn new(content: models::ReportContent, creator_info: models::ReportAccountInfo, info: models::ReportDetailedInfo, target_info: models::ReportAccountInfo) -> ReportDetailed {
        ReportDetailed {
            chat_info: None,
            content,
            creator_info,
            info,
            target_info,
        }
    }
}

