/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReportTypeNumber : Values:  * ProfileName = 0 * ProfileText = 1 * ProfileContent = 2 * ChatMessage = 3 * CustomReport = values from 64 to 127
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportTypeNumber {
    /// This is i8 so that max value is 127. That makes SQLite to store the value using single byte.
    #[serde(rename = "n")]
    pub n: i32,
}

impl ReportTypeNumber {
    /// Values:  * ProfileName = 0 * ProfileText = 1 * ProfileContent = 2 * ChatMessage = 3 * CustomReport = values from 64 to 127
    pub fn new(n: i32) -> ReportTypeNumber {
        ReportTypeNumber {
            n,
        }
    }
}

