/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaveInfoBanners {
    #[serde(rename = "current", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current: Option<Option<Box<models::InfoBannersConfig>>>,
    #[serde(rename = "new")]
    pub new: Box<models::InfoBannersConfig>,
}

impl SaveInfoBanners {
    pub fn new(new: models::InfoBannersConfig) -> SaveInfoBanners {
        SaveInfoBanners {
            current: None,
            new: Box::new(new),
        }
    }
}

