/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityContentVerificationQueueAdminItem {
    #[serde(rename = "account_id")]
    pub account_id: Box<models::AccountId>,
    #[serde(rename = "security_content")]
    pub security_content: Box<models::ContentId>,
    #[serde(rename = "verification_data")]
    pub verification_data: String,
    #[serde(rename = "verification_method")]
    pub verification_method: String,
}

impl SecurityContentVerificationQueueAdminItem {
    pub fn new(account_id: models::AccountId, security_content: models::ContentId, verification_data: String, verification_method: String) -> SecurityContentVerificationQueueAdminItem {
        SecurityContentVerificationQueueAdminItem {
            account_id: Box::new(account_id),
            security_content: Box::new(security_content),
            verification_data,
            verification_method,
        }
    }
}

