/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityContent {
    #[serde(rename = "content_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_id: Option<Option<Box<models::ContentInfo>>>,
}

impl SecurityContent {
    pub fn new() -> SecurityContent {
        SecurityContent {
            content_id: None,
        }
    }
}

