/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeenMessageList {
    #[serde(rename = "messages")]
    pub messages: Vec<models::SeenMessage>,
}

impl SeenMessageList {
    pub fn new(messages: Vec<models::SeenMessage>) -> SeenMessageList {
        SeenMessageList {
            messages,
        }
    }
}

