/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SendMessageToAccount {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "receiver")]
    pub receiver: Box<crate::models::AccountId>,
    #[serde(rename = "receiver_public_key_id")]
    pub receiver_public_key_id: Box<crate::models::PublicKeyId>,
    #[serde(rename = "receiver_public_key_version")]
    pub receiver_public_key_version: Box<crate::models::PublicKeyVersion>,
}

impl SendMessageToAccount {
    pub fn new(message: String, receiver: crate::models::AccountId, receiver_public_key_id: crate::models::PublicKeyId, receiver_public_key_version: crate::models::PublicKeyVersion) -> SendMessageToAccount {
        SendMessageToAccount {
            message,
            receiver: Box::new(receiver),
            receiver_public_key_id: Box::new(receiver_public_key_id),
            receiver_public_key_version: Box::new(receiver_public_key_version),
        }
    }
}


