/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendCustomEmail {
    #[serde(rename = "email_id")]
    pub email_id: Box<models::CustomEmailId>,
    #[serde(rename = "target_group")]
    pub target_group: models::CustomEmailTargetGroup,
}

impl SendCustomEmail {
    pub fn new(email_id: models::CustomEmailId, target_group: models::CustomEmailTargetGroup) -> SendCustomEmail {
        SendCustomEmail {
            email_id: Box::new(email_id),
            target_group,
        }
    }
}

