/*
 * pihka-backend
 *
 * Pihka backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnixTime {
    #[serde(rename = "unix_time")]
    pub unix_time: i64,
}

impl UnixTime {
    pub fn new(unix_time: i64) -> UnixTime {
        UnixTime {
            unix_time,
        }
    }
}

