/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProfileNameReport {
    #[serde(rename = "profile_name")]
    pub profile_name: String,
    #[serde(rename = "target")]
    pub target: Box<models::AccountId>,
}

impl UpdateProfileNameReport {
    pub fn new(profile_name: String, target: models::AccountId) -> UpdateProfileNameReport {
        UpdateProfileNameReport {
            profile_name,
            target: Box::new(target),
        }
    }
}

