/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateAssociationMembershipType : Input for admin to change membership type of an existing entry.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAssociationMembershipType {
    #[serde(rename = "member")]
    pub member: Box<models::AccountId>,
    #[serde(rename = "membership_type")]
    pub membership_type: i32,
}

impl UpdateAssociationMembershipType {
    /// Input for admin to change membership type of an existing entry.
    pub fn new(member: models::AccountId, membership_type: i32) -> UpdateAssociationMembershipType {
        UpdateAssociationMembershipType {
            member: Box::new(member),
            membership_type,
        }
    }
}

