/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateChatMessageReport {
    #[serde(rename = "messages")]
    pub messages: Vec<models::ChatMessageReportData>,
    #[serde(rename = "target")]
    pub target: Box<models::AccountId>,
}

impl UpdateChatMessageReport {
    pub fn new(messages: Vec<models::ChatMessageReportData>, target: models::AccountId) -> UpdateChatMessageReport {
        UpdateChatMessageReport {
            messages,
            target: Box::new(target),
        }
    }
}

