/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCustomEmail {
    #[serde(rename = "id")]
    pub id: Box<models::CustomEmailId>,
    /// Translation with \"default\" locale must exist.
    #[serde(rename = "translations")]
    pub translations: Vec<models::CustomEmailTranslation>,
}

impl UpdateCustomEmail {
    pub fn new(id: models::CustomEmailId, translations: Vec<models::CustomEmailTranslation>) -> UpdateCustomEmail {
        UpdateCustomEmail {
            id: Box::new(id),
            translations,
        }
    }
}

