/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCustomReportBoolean {
    #[serde(rename = "custom_report_id")]
    pub custom_report_id: i32,
    #[serde(rename = "target")]
    pub target: Box<models::AccountId>,
    #[serde(rename = "value")]
    pub value: bool,
}

impl UpdateCustomReportBoolean {
    pub fn new(custom_report_id: i32, target: models::AccountId, value: bool) -> UpdateCustomReportBoolean {
        UpdateCustomReportBoolean {
            custom_report_id,
            target: Box::new(target),
            value,
        }
    }
}

