/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateNewsTranslation {
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "current_version")]
    pub current_version: Box<models::NewsTranslationVersion>,
    #[serde(rename = "title")]
    pub title: String,
}

impl UpdateNewsTranslation {
    pub fn new(body: String, current_version: models::NewsTranslationVersion, title: String) -> UpdateNewsTranslation {
        UpdateNewsTranslation {
            body,
            current_version: Box::new(current_version),
            title,
        }
    }
}

