/*
 * afrodite-backend
 *
 * Dating app backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerificationMethodsConfig {
    #[serde(rename = "account", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account: Option<Option<Box<models::AccountVerificationMethodsConfig>>>,
}

impl VerificationMethodsConfig {
    pub fn new() -> VerificationMethodsConfig {
        VerificationMethodsConfig {
            account: None,
        }
    }
}

