[package]
name = "server_data_account"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { workspace = true }

config = { path = "../config" }
model = { path = "../model" }
model_account = { path = "../model_account" }
server_common = { path = "../server_common" }
server_data = { path = "../server_data" }

database_account = { path = "../database_account" }

simple_backend = { path = "../simple_backend" }
