[package]
name = "server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { version = "1.1.2", features = ["v4", "serde"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["sync"] }
tokio-util = { version = "0.7.7", features = ["io"]}
hyper = { version = "0.14", features = ["full"] }
axum = { version = "0.6", features = ["headers", "ws", "macros"] }
tracing = { version = "0.1" }
headers = "0.3.8"
reqwest = { version = "0.11", features = ["json"] }

utoipa = { version = "3.0.1", features = ["axum_extras", "uuid"] }
utoipa-swagger-ui = { version = "3.0.1", features = ["axum"] }

thiserror = "1.0.37"
error-stack = "0.4"

async-trait = "0.1.66"

nalgebra = "0.32.2"

num_cpus = "1.16.0"
nix = { version = "0.26.2", default-features = false, features = ["signal"] }

manager_model = { path = "../app-manager/crates/manager_model" }

utils = { path = "../utils" }
config = { path = "../config" }
database = { path = "../database" }
model = { path = "../model" }
api_internal = { path = "../api_internal" }

simple_backend = { path = "../simple_backend" }
simple_backend_utils = { path = "../simple_backend_utils" }
simple_backend_config = { path = "../simple_backend_config" }
simple_backend_model = { path = "../simple_backend_model" }
simple_backend_database = { path = "../simple_backend_database" }
